### ISSUE TITLE
keyboard import creates a lot of issues

### ISSUE THREAD

**Issue by BatSmacker84** [jordicastro/software_engineering#19]
On MacOS the package suddenly wants a ton of new packages:
```
pyobjc==10.1
pyobjc-core==10.1
pyobjc-framework-Accessibility==10.1
...plus another ~60
```
On Linux (and maybe MacOS, too) the program now requires root privilege in order to run.
This is a massive security vulnerability, so it is best to be avoided unless absolutely needed.

I already came up with a fix for removing the package and re-implementing functionality:
By replacing this in splash.py:
```python
# stays open for 5 seconds
    slp_segs = 50 # Number of segments
    slp_len = 5 # 5 seconds
    for i in range(slp_segs):
        time.sleep(slp_len/slp_segs)

        # allows the splash screen to be closed by pressing the escape key
        if keyboard.is_pressed('escape'):
            break
```
with this:
```python
# loop for 5 seconds to show the splash screen
    # Also wait for possible user input
    start_time = time.time()
    while time.time() - start_time < 5:
        events()
```
The functionality of pressing escape to close the splash screen in maintained, but the keyboard package is no longer needed. Removing the other mention of keyboard in main.py and replacing it with something similar to close the main window is also necessary.

**Comment by BatSmacker84** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove "keyboard" package](https://trello.com/c/cGYgLkwt/22-remove-keyboard-package)

**Comment by wrrath** [comment]
I went ahead and used the pygame keyboard functionality instead of keyboard and it'll be implented in the main branch on my next pull into main.

**Comment by wrrath** [comment]
Merged @BatSmacker84 fix.
